name: Build
on: 
  pull_request:
  push:
    branches:
      - master
      - development
jobs:
  build:
    name: Yarn Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc

      - name: Install Deps
        run: yarn install --frozen-lockfile
          
      - name: Clean API
        run: yarn clean:api  
          
      - name: Generate API
        run: yarn gen:api
          
      - name: Build production bundle
        run: yarn build
